/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.icesp.cadastro.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the cadastroUsuario service. Represents a row in the &quot;icesp_cadastroUsuario&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.icesp.cadastro.model.impl.cadastroUsuarioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.icesp.cadastro.model.impl.cadastroUsuarioImpl}.
 * </p>
 *
 * @author ln00704
 * @see cadastroUsuario
 * @see com.icesp.cadastro.model.impl.cadastroUsuarioImpl
 * @see com.icesp.cadastro.model.impl.cadastroUsuarioModelImpl
 * @generated
 */
public interface cadastroUsuarioModel extends BaseModel<cadastroUsuario> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cadastro usuario model instance should use the {@link cadastroUsuario} interface instead.
	 */

	/**
	 * Returns the primary key of this cadastro usuario.
	 *
	 * @return the primary key of this cadastro usuario
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this cadastro usuario.
	 *
	 * @param primaryKey the primary key of this cadastro usuario
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the cpf of this cadastro usuario.
	 *
	 * @return the cpf of this cadastro usuario
	 */
	@AutoEscape
	public String getCpf();

	/**
	 * Sets the cpf of this cadastro usuario.
	 *
	 * @param cpf the cpf of this cadastro usuario
	 */
	public void setCpf(String cpf);

	/**
	 * Returns the rg of this cadastro usuario.
	 *
	 * @return the rg of this cadastro usuario
	 */
	@AutoEscape
	public String getRg();

	/**
	 * Sets the rg of this cadastro usuario.
	 *
	 * @param rg the rg of this cadastro usuario
	 */
	public void setRg(String rg);

	/**
	 * Returns the nome of this cadastro usuario.
	 *
	 * @return the nome of this cadastro usuario
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this cadastro usuario.
	 *
	 * @param nome the nome of this cadastro usuario
	 */
	public void setNome(String nome);

	/**
	 * Returns the user name of this cadastro usuario.
	 *
	 * @return the user name of this cadastro usuario
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this cadastro usuario.
	 *
	 * @param userName the user name of this cadastro usuario
	 */
	public void setUserName(String userName);

	/**
	 * Returns the sobrenome of this cadastro usuario.
	 *
	 * @return the sobrenome of this cadastro usuario
	 */
	@AutoEscape
	public String getSobrenome();

	/**
	 * Sets the sobrenome of this cadastro usuario.
	 *
	 * @param sobrenome the sobrenome of this cadastro usuario
	 */
	public void setSobrenome(String sobrenome);

	/**
	 * Returns the email of this cadastro usuario.
	 *
	 * @return the email of this cadastro usuario
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this cadastro usuario.
	 *
	 * @param email the email of this cadastro usuario
	 */
	public void setEmail(String email);

	/**
	 * Returns the emailconfir of this cadastro usuario.
	 *
	 * @return the emailconfir of this cadastro usuario
	 */
	@AutoEscape
	public String getEmailconfir();

	/**
	 * Sets the emailconfir of this cadastro usuario.
	 *
	 * @param emailconfir the emailconfir of this cadastro usuario
	 */
	public void setEmailconfir(String emailconfir);

	/**
	 * Returns the senha of this cadastro usuario.
	 *
	 * @return the senha of this cadastro usuario
	 */
	@AutoEscape
	public String getSenha();

	/**
	 * Sets the senha of this cadastro usuario.
	 *
	 * @param senha the senha of this cadastro usuario
	 */
	public void setSenha(String senha);

	/**
	 * Returns the senhaconfir of this cadastro usuario.
	 *
	 * @return the senhaconfir of this cadastro usuario
	 */
	@AutoEscape
	public String getSenhaconfir();

	/**
	 * Sets the senhaconfir of this cadastro usuario.
	 *
	 * @param senhaconfir the senhaconfir of this cadastro usuario
	 */
	public void setSenhaconfir(String senhaconfir);

	/**
	 * Returns the celular of this cadastro usuario.
	 *
	 * @return the celular of this cadastro usuario
	 */
	@AutoEscape
	public String getCelular();

	/**
	 * Sets the celular of this cadastro usuario.
	 *
	 * @param celular the celular of this cadastro usuario
	 */
	public void setCelular(String celular);

	/**
	 * Returns the sexo of this cadastro usuario.
	 *
	 * @return the sexo of this cadastro usuario
	 */
	@AutoEscape
	public String getSexo();

	/**
	 * Sets the sexo of this cadastro usuario.
	 *
	 * @param sexo the sexo of this cadastro usuario
	 */
	public void setSexo(String sexo);

	/**
	 * Returns the date of this cadastro usuario.
	 *
	 * @return the date of this cadastro usuario
	 */
	public Date getDate();

	/**
	 * Sets the date of this cadastro usuario.
	 *
	 * @param date the date of this cadastro usuario
	 */
	public void setDate(Date date);

	/**
	 * Returns the cep of this cadastro usuario.
	 *
	 * @return the cep of this cadastro usuario
	 */
	@AutoEscape
	public String getCep();

	/**
	 * Sets the cep of this cadastro usuario.
	 *
	 * @param cep the cep of this cadastro usuario
	 */
	public void setCep(String cep);

	/**
	 * Returns the estado of this cadastro usuario.
	 *
	 * @return the estado of this cadastro usuario
	 */
	@AutoEscape
	public String getEstado();

	/**
	 * Sets the estado of this cadastro usuario.
	 *
	 * @param estado the estado of this cadastro usuario
	 */
	public void setEstado(String estado);

	/**
	 * Returns the cidade of this cadastro usuario.
	 *
	 * @return the cidade of this cadastro usuario
	 */
	@AutoEscape
	public String getCidade();

	/**
	 * Sets the cidade of this cadastro usuario.
	 *
	 * @param cidade the cidade of this cadastro usuario
	 */
	public void setCidade(String cidade);

	/**
	 * Returns the rua of this cadastro usuario.
	 *
	 * @return the rua of this cadastro usuario
	 */
	@AutoEscape
	public String getRua();

	/**
	 * Sets the rua of this cadastro usuario.
	 *
	 * @param rua the rua of this cadastro usuario
	 */
	public void setRua(String rua);

	/**
	 * Returns the profissao of this cadastro usuario.
	 *
	 * @return the profissao of this cadastro usuario
	 */
	@AutoEscape
	public String getProfissao();

	/**
	 * Sets the profissao of this cadastro usuario.
	 *
	 * @param profissao the profissao of this cadastro usuario
	 */
	public void setProfissao(String profissao);

	/**
	 * Returns the hospital of this cadastro usuario.
	 *
	 * @return the hospital of this cadastro usuario
	 */
	@AutoEscape
	public String getHospital();

	/**
	 * Sets the hospital of this cadastro usuario.
	 *
	 * @param hospital the hospital of this cadastro usuario
	 */
	public void setHospital(String hospital);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(cadastroUsuario cadastroUsuario);

	public int hashCode();

	public CacheModel<cadastroUsuario> toCacheModel();

	public cadastroUsuario toEscapedModel();

	public String toString();

	public String toXmlString();
}